apiVersion: v1
kind: Endpoints
metadata:
  name: short
  namespace: external
subsets:
  - addresses:
      - ip: 192.168.102.85
    ports:
      - name: default
        port: 3001
        protocol: TCP
        