---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secured-chain
  namespace: default
spec:
  chain:
    middlewares:
      - name: rate-limit
      - name: secure-headers
