apiVersion: v1
kind: Endpoints
metadata:
  name: container
  namespace: external
subsets:
  - addresses:
      - ip: 10.40.0.40
    ports:
      - name: default
        port: 9000
        protocol: TCP
