apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - charts
  - weave-gitops-dashboard
patchesStrategicMerge:
  - ./gotk-patches.yaml
