---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.1
    hajimari:
      defaultEnable: true
      namespaceSelector:
        matchNames:
          - default
          - external
          - networking
      name: "IT"
      customApps:
        - name: Tristian Devbin
          url: ${SECRET_DEVBIN_URL}
          icon: microsoft-visual-studio-code
        - name: Tristian OCI
          url: ${SECRET_OCI_URL}
          icon: microsoft-visual-studio-code
        - name: Password
          url: ${SECRET_PASS_DOMAIN}
          icon: onepassword
        - name: ChatGPT UI
          url: ${SECRET_GPT_DOMAIN}
          icon: chat-plus
        - name: Casper
          url: ${SECRET_CASPER_DOMAIN}
          icon: post
        - name: Oracle DNS
          url: ${SECRET_ORACLE_DNS_DOMAIN}
          icon: dns-outline
        - name: Oracle Remote
          url: ${SECRET_ORACLE_REMOTE_DOMAIN}
          icon: key
        - name: Oracle Jenkins
          url: ${SECRET_ORACLE_JENKINS_DOMAIN}
          icon: source-branch-sync
      groups:
        - name: AI
          links:
            - name: ChatGPT
              url: "https://chat.openai.com"
        - name: Provider
          links:
            - name: Google Cloud
              url: "https://cloud.google.com"
            - name: Cloudflare
              url: "https://dash.cloudflare.com"
            - name: DigitalOcean
              url: "https://cloud.digitalocean.com"
            - name: Oracle
              url: "https://cloud.oracle.com"
            - name: AWS
              url: "https://aws.amazon.com/"
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
            - name: Slack
              url: "https://slack.com/signin"
        - name: Cloud
          links:
            - name: Dropbox
              url: "https://dropbox.com"
            - name: Drive
              url: "https://drive.google.com"
        - name: Design
          links:
            - name: Awwwards
              url: "https://awwwards.com"
            - name: Dribbble
              url: "https://dribbble.com"
            - name: Muz.li
              url: "https://medium.muz.li/"
        - name: Dev
          links:
            - name: Codepen
              url: "https://codepen.io/"
            - name: Devdocs
              url: "https://devdocs.io"
            - name: Devhints
              url: "https://devhints.io"
        - name: Lifestyle
          links:
            - name: Design Milk
              url: "https://design-milk.com/category/interior-design/"
            - name: Dwell
              url: "https://www.dwell.com/"
            - name: Freshome
              url: "https://www.mymove.com/freshome/"
        - name: Media
          links:
            - name: Spotify
              url: "http://browse.spotify.com"
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
        - name: Reading
          links:
            - name: Medium
              url: "http://medium.com"
            - name: Reddit
              url: "http://reddit.com"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            - name: The Verge
              url: "https://theverge.com/"
            - name: MIT Technology Review
              url: "https://www.technologyreview.com/"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "${SECRET_START_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "${SECRET_START_DOMAIN}"
            secretName: "hajimari-tls"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
